refactor: version validation (#454)
* refactor: version validation

* fix: fetch tags

* refactor: change default to patch

* fix: syntax

* fix: fetch tags

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -10,7 +10,7 @@ on:
       release_kind:
         description: 'Select the release kind: major, minor, or patch'
         required: true
-        default: 'minor'
+        default: 'patch'
         type: choice
         options:
           - major
@@ -21,8 +21,27 @@ jobs:
   release:
     runs-on: ubuntu-latest
     steps:
+      - name: Validate version format
+        id: validate_version
+        run: |
+          if ! [[ "${{ inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Invalid version format. Please use Semantic Versioning (SemVer) format, e.g., 0.1.0"
+            exit 1
+          fi
+
       - name: Checkout code
         uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+          fetch-tags: true
+
+      - name: Check if version exists
+        id: check_version
+        run: |
+          if git rev-parse "v${{ inputs.version }}" >/dev/null 2>&1; then
+            echo "Version already exists. Aborting release."
+            exit 1
+          fi
 
       - name: Set up Node.js
         uses: actions/setup-node@v2
